### PR TITLE
Issue 98

### PR DESCRIPTION
**Pull request by aivogft**
PR to merge issue 98

### CODE REVIEW

**Comment by geoff-gft** [comment]
some issues around local_repo
example of response:
` resp {"repo_name": "<git.repo.base.Repo '/tmp/tmpjubninsb/.git'>", "project_id": "shared-ec-xe68ff2g", "head_link": "https://source.cloud.google.com/shared-ec-xe68ff2g/<git.repo.base.Repo '/tmp/tmpjubninsb/.git'>/+/master:", "path_link": "shared-ec-xe68ff2g/<git.repo.base.Repo '/tmp/tmpjubninsb/.git'>/master//", "browser_link": "https://source.cloud.google.com/shared-ec-xe68ff2g/<git.repo.base.Repo '/tmp/tmpjubninsb/.git'>", "git_clone": "git clone https://source.cloud.google.com/p/shared-ec-xe68ff2g/r/<git.repo.base.Repo '/tmp/tmpjubninsb/.git'>", "cloud_sdk": "gcloud source repos clone <git.repo.base.Repo '/tmp/tmpjubninsb/.git'> --project=shared-ec-xe68ff2g"}
`
we have this <git.repo.base.Repo '/tmp/tmpjubninsb/.git'> form of string which is not what we want

**Comment by Salles-FA** [comment]
@geoff-gft ,

There's a new issue with the mock image. This issue wasn't in the PR #181, but it's still related to issue #180. 

As it isn't an issue on `master`, I won't reopen #180. But, please, have a look if you could fix it.

```
gcp-dac_1          | [2020-11-26 17:21:43 +0000] [9] [ERROR] Exception in worker process
gcp-dac_1          | Traceback (most recent call last):
gcp-dac_1          |   File "/usr/local/lib/python3.6/site-packages/connexion/apis/abstract.py", line 209, in add_paths
gcp-dac_1          |     self.add_operation(path, method)
gcp-dac_1          |   File "/usr/local/lib/python3.6/site-packages/connexion/apis/abstract.py", line 173, in add_operation
gcp-dac_1          |     pass_context_arg_name=self.pass_context_arg_name
gcp-dac_1          |   File "/usr/local/lib/python3.6/site-packages/connexion/operations/__init__.py", line 8, in make_operation
gcp-dac_1          |     return spec.operation_cls.from_spec(spec, *args, **kwargs)
gcp-dac_1          |   File "/usr/local/lib/python3.6/site-packages/connexion/operations/openapi.py", line 138, in from_spec
gcp-dac_1          |     **kwargs
gcp-dac_1          |   File "/usr/local/lib/python3.6/site-packages/connexion/operations/openapi.py", line 89, in __init__
gcp-dac_1          |     pass_context_arg_name=pass_context_arg_name
gcp-dac_1          |   File "/usr/local/lib/python3.6/site-packages/connexion/operations/abstract.py", line 96, in __init__
gcp-dac_1          |     self._resolution = resolver.resolve(self)
gcp-dac_1          |   File "/usr/local/lib/python3.6/site-packages/connexion/resolver.py", line 40, in resolve
gcp-dac_1          |     return Resolution(self.resolve_function_from_operation_id(operation_id), operation_id)
gcp-dac_1          |   File "/usr/local/lib/python3.6/site-packages/connexion/resolver.py", line 64, in resolve_function_from_operation_id
gcp-dac_1          |     raise ResolverError(msg, sys.exc_info())
gcp-dac_1          | connexion.exceptions.ResolverError: <ResolverError: Cannot resolve operationId "gcpdac.onboarding.get_repo_uri"! Import error was "No module named 'gcloud'">
gcp-dac_1          |
gcp-dac_1          | During handling of the above exception, another exception occurred:
gcp-dac_1          | 
gcp-dac_1          | Traceback (most recent call last):
gcp-dac_1          |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
gcp-dac_1          |     worker.init_process()
gcp-dac_1          |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
gcp-dac_1          |     self.load_wsgi()
gcp-dac_1          |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
gcp-dac_1          |     self.wsgi = self.app.wsgi()
gcp-dac_1          |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
gcp-dac_1          |     self.callable = self.load()
gcp-dac_1          |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
gcp-dac_1          |     return self.load_wsgiapp()
gcp-dac_1          |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
gcp-dac_1          |     return util.import_app(self.app_uri)
gcp-dac_1          |   File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
gcp-dac_1          |     mod = importlib.import_module(module)
gcp-dac_1          |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
gcp-dac_1          |     return _bootstrap._gcd_import(name[level:], package, level)
gcp-dac_1          |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
gcp-dac_1          |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
gcp-dac_1          |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
gcp-dac_1          |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
gcp-dac_1          |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
gcp-dac_1          |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
gcp-dac_1          |   File "/srv/app.py", line 13, in <module>
gcp-dac_1          |     connex_app.add_api('openapi.yml', strict_validation=False)
gcp-dac_1          |   File "/usr/local/lib/python3.6/site-packages/connexion/apps/flask_app.py", line 57, in add_api
gcp-dac_1          |     api = super(FlaskApp, self).add_api(specification, **kwargs)
gcp-dac_1          |   File "/usr/local/lib/python3.6/site-packages/connexion/apps/abstract.py", line 156, in add_api
gcp-dac_1          |     options=api_options.as_dict())
gcp-dac_1          |   File "/usr/local/lib/python3.6/site-packages/connexion/apis/abstract.py", line 111, in __init__
gcp-dac_1          |     self.add_paths()
gcp-dac_1          |   File "/usr/local/lib/python3.6/site-packages/connexion/apis/abstract.py", line 216, in add_paths
gcp-dac_1          |     self._handle_add_operation_error(path, method, err.exc_info)
gcp-dac_1          |   File "/usr/local/lib/python3.6/site-packages/connexion/apis/abstract.py", line 231, in _handle_add_operation_error
gcp-dac_1          |     raise value.with_traceback(traceback)
gcp-dac_1          |   File "/usr/local/lib/python3.6/site-packages/connexion/resolver.py", line 61, in resolve_function_from_operation_id
gcp-dac_1          |     return self.function_resolver(operation_id)
gcp-dac_1          |   File "/usr/local/lib/python3.6/site-packages/connexion/utils.py", line 123, in get_function_from_name
gcp-dac_1          |     raise last_import_error
gcp-dac_1          |   File "/usr/local/lib/python3.6/site-packages/connexion/utils.py", line 111, in get_function_from_name
gcp-dac_1          |     module = importlib.import_module(module_name)
gcp-dac_1          |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
gcp-dac_1          |     return _bootstrap._gcd_import(name[level:], package, level)
gcp-dac_1          |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
gcp-dac_1          |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
gcp-dac_1          |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
gcp-dac_1          |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
gcp-dac_1          |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
gcp-dac_1          |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
gcp-dac_1          |   File "/srv/gcpdac/onboarding.py", line 4, in <module>
gcp-dac_1          |     from gcloud import resource_manager
gcp-dac_1          | ModuleNotFoundError: No module named 'gcloud'
gcp-dac_1          | [2020-11-26 17:21:43 +0000] [9] [INFO] Worker exiting (pid: 9)
gcp-dac_1          | basedir: /srv
gcp-dac_1          | DEBUG: True
gcp-dac_1          | [2020-11-26 17:21:43 +0000] [6] [INFO] Shutting down: Master
gcp-dac_1          | [2020-11-26 17:21:43 +0000] [6] [INFO] Reason: Worker failed to boot.
tb-eagle-console_gcp-dac_1 exited with code 3

```

**Review by Salles-FA — CHANGES_REQUESTED** [review]
mock version is failing to initialize

**Comment by Salles-FA** [comment]
@aivogft, have a look into the Codacy erros, please. They're required to be fixed before merging into master.

**Review by Salles-FA — APPROVED** [review]

**Review by sunderhill-gft — APPROVED** [review]
Looks good to me

**Pull request merged**
